import { McuRecordInput, DcuRecordInput } from '@cardiowork/shared';

export interface DemoWorkerData {
  worker: {
    id: string;
    pseudonymId: string;
    nameSynthetic: string;
    age: number;
    gender: 'MALE' | 'FEMALE';
    department: string;
    jobTitle: string;
    jobHazardCategory: string;
    shiftPattern: string;
    tenureMonths: number;
    isActive: boolean;
  };
  mcuRecords: McuRecordInput[];
  dcuRecords: DcuRecordInput[];
}

export const DEMO_WORKERS: Record<string, DemoWorkerData> = {
  "W-00192": {
    "worker": {
      "id": "worker-uuid-00192",
      "pseudonymId": "W-00192",
      "nameSynthetic": "Eko Saputra",
      "age": 49,
      "gender": "MALE",
      "department": "Drilling Operations",
      "jobTitle": "Toolpusher",
      "jobHazardCategory": "HIGH",
      "shiftPattern": "12H_DAY_NIGHT_ROTATION",
      "tenureMonths": 21,
      "isActive": true
    },
    "mcuRecords": [
      {
        "id": "mcu-uuid-W-00192-2024",
        "workerId": "worker-uuid-00192",
        "examinationDate": "2024-07-11",
        "heightCm": 173.2,
        "weightKg": 73.4,
        "bmi": 24.5,
        "waistCircumferenceCm": 80.7,
        "systolicBp": 129,
        "diastolicBp": 77,
        "restingHeartRate": 71,
        "fastingGlucoseMgdl": 122,
        "hba1cPercent": 8.2,
        "totalCholesterolMgdl": 235,
        "ldlCholesterolMgdl": 140,
        "hdlCholesterolMgdl": 64,
        "triglyceridesMgdl": 178,
        "creatinineMgdl": 1.42,
        "egfr": 57.5,
        "uricAcidMgdl": 5.3,
        "smokingStatus": "NON_SMOKER",
        "packYears": 0.0,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": false,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "NORMAL",
        "overallFitnessStatus": "FIT"
      },
      {
        "id": "mcu-uuid-W-00192-2025",
        "workerId": "worker-uuid-00192",
        "examinationDate": "2025-09-14",
        "heightCm": 173.2,
        "weightKg": 74.4,
        "bmi": 24.8,
        "waistCircumferenceCm": 82.1,
        "systolicBp": 131,
        "diastolicBp": 88,
        "restingHeartRate": 63,
        "fastingGlucoseMgdl": 91,
        "hba1cPercent": 7.4,
        "totalCholesterolMgdl": 227,
        "ldlCholesterolMgdl": 159,
        "hdlCholesterolMgdl": 48,
        "triglyceridesMgdl": 132,
        "creatinineMgdl": 1.29,
        "egfr": 59.8,
        "uricAcidMgdl": 5.7,
        "smokingStatus": "NON_SMOKER",
        "packYears": 0.0,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": false,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "BORDERLINE",
        "overallFitnessStatus": "FIT"
      },
      {
        "id": "mcu-uuid-W-00192-2026",
        "workerId": "worker-uuid-00192",
        "examinationDate": "2026-07-07",
        "heightCm": 173.2,
        "weightKg": 75.0,
        "bmi": 25.0,
        "waistCircumferenceCm": 84.8,
        "systolicBp": 118,
        "diastolicBp": 74,
        "restingHeartRate": 73,
        "fastingGlucoseMgdl": 101,
        "hba1cPercent": 7.7,
        "totalCholesterolMgdl": 186,
        "ldlCholesterolMgdl": 105,
        "hdlCholesterolMgdl": 60,
        "triglyceridesMgdl": 178,
        "creatinineMgdl": 0.69,
        "egfr": 73.8,
        "uricAcidMgdl": 8.2,
        "smokingStatus": "NON_SMOKER",
        "packYears": 0.0,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": false,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "NORMAL",
        "overallFitnessStatus": "FIT"
      }
    ],
    "dcuRecords": [
      {
        "id": "dcu-W-00192-20261127",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-11-27T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 121,
        "diastolicBp": 75,
        "restingHeartRate": 85,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.0,
        "sleepHoursLast24h": 5.8,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 294,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261128",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-11-28T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 126,
        "diastolicBp": 83,
        "restingHeartRate": 82,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 5.3,
        "caffeineIntakeCups": 3,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 265,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261129",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-11-29T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 114,
        "diastolicBp": 73,
        "restingHeartRate": 83,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 6.9,
        "caffeineIntakeCups": 4,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 285,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261130",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-11-30T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 123,
        "diastolicBp": 77,
        "restingHeartRate": 79,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 5.5,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 266,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261201",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-01T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 120,
        "diastolicBp": 76,
        "restingHeartRate": 78,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 4.7,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 323,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261204",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-04T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 121,
        "diastolicBp": 79,
        "restingHeartRate": 75,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 7.9,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 238,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261205",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-05T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 120,
        "diastolicBp": 70,
        "restingHeartRate": 74,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 6.1,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 260,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261206",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-06T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 119,
        "diastolicBp": 70,
        "restingHeartRate": 69,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.0,
        "sleepHoursLast24h": 6.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 219,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261207",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-07T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 109,
        "diastolicBp": 70,
        "restingHeartRate": 73,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 7.3,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 269,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261209",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-09T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 114,
        "diastolicBp": 69,
        "restingHeartRate": 61,
        "spo2Percent": 95,
        "bodyTemperatureC": 37.1,
        "sleepHoursLast24h": 6.7,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 254,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261210",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-10T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 113,
        "diastolicBp": 71,
        "restingHeartRate": 75,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 7.8,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 233,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261212",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-12T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 119,
        "diastolicBp": 77,
        "restingHeartRate": 76,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 7.7,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 227,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261213",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-13T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 117,
        "diastolicBp": 71,
        "restingHeartRate": 75,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.2,
        "sleepHoursLast24h": 7.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 227,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261214",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-14T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 108,
        "diastolicBp": 71,
        "restingHeartRate": 71,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 6.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 249,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261215",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-15T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 115,
        "diastolicBp": 74,
        "restingHeartRate": 70,
        "spo2Percent": 95,
        "bodyTemperatureC": 36.4,
        "sleepHoursLast24h": 6.6,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 229,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261216",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-16T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 117,
        "diastolicBp": 73,
        "restingHeartRate": 70,
        "spo2Percent": 96,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 7.0,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 281,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261217",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-17T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 122,
        "diastolicBp": 79,
        "restingHeartRate": 88,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 5.7,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 310,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261218",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-18T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 133,
        "diastolicBp": 88,
        "restingHeartRate": 83,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 3.5,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 307,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261219",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-19T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 120,
        "diastolicBp": 77,
        "restingHeartRate": 73,
        "spo2Percent": 97,
        "bodyTemperatureC": 37.2,
        "sleepHoursLast24h": 5.7,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 305,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261221",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-21T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 122,
        "diastolicBp": 70,
        "restingHeartRate": 82,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.2,
        "sleepHoursLast24h": 5.0,
        "caffeineIntakeCups": 3,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 250,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261222",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-22T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 133,
        "diastolicBp": 79,
        "restingHeartRate": 84,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 4.6,
        "caffeineIntakeCups": 4,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 258,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261223",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-23T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 126,
        "diastolicBp": 77,
        "restingHeartRate": 72,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.0,
        "sleepHoursLast24h": 4.9,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 340,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261224",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-24T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 137,
        "diastolicBp": 84,
        "restingHeartRate": 71,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 2.7,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 285,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261225",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-25T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 140,
        "diastolicBp": 87,
        "restingHeartRate": 75,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 4.2,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 349,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261226",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-26T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 140,
        "diastolicBp": 82,
        "restingHeartRate": 76,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 2.9,
        "caffeineIntakeCups": 4,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 322,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261227",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-27T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 127,
        "diastolicBp": 78,
        "restingHeartRate": 81,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.1,
        "sleepHoursLast24h": 4.8,
        "caffeineIntakeCups": 4,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 293,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261228",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-28T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 126,
        "diastolicBp": 75,
        "restingHeartRate": 80,
        "spo2Percent": 98,
        "bodyTemperatureC": 35.9,
        "sleepHoursLast24h": 3.8,
        "caffeineIntakeCups": 3,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 335,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261229",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-29T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 127,
        "diastolicBp": 79,
        "restingHeartRate": 74,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 4.5,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 313,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00192-20261230",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-30T18:30:00Z",
        "shiftType": "NIGHT_SHIFT",
        "systolicBp": 132,
        "diastolicBp": 84,
        "restingHeartRate": 79,
        "spo2Percent": 100,
        "bodyTemperatureC": 36.1,
        "sleepHoursLast24h": 4.3,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 350,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00192-20261231",
        "workerId": "worker-uuid-00192",
        "recordedAt": "2026-12-31T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 111,
        "diastolicBp": 64,
        "restingHeartRate": 73,
        "spo2Percent": 100,
        "bodyTemperatureC": 36.8,
        "sleepHoursLast24h": 7.3,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 0,
        "reactionTimeMs": 218,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      }
    ]
  },
  "W-00189": {
    "worker": {
      "id": "worker-uuid-00189",
      "pseudonymId": "W-00189",
      "nameSynthetic": "Joko Wijaya",
      "age": 34,
      "gender": "MALE",
      "department": "Marine & Offshore Logistics",
      "jobTitle": "Crane Operator",
      "jobHazardCategory": "MEDIUM",
      "shiftPattern": "DAY_SHIFT_ONLY",
      "tenureMonths": 130,
      "isActive": true
    },
    "mcuRecords": [
      {
        "id": "mcu-uuid-W-00189-2024",
        "workerId": "worker-uuid-00189",
        "examinationDate": "2024-06-07",
        "heightCm": 171.0,
        "weightKg": 74.8,
        "bmi": 25.6,
        "waistCircumferenceCm": 87.8,
        "systolicBp": 131,
        "diastolicBp": 77,
        "restingHeartRate": 81,
        "fastingGlucoseMgdl": 73,
        "hba1cPercent": 6.7,
        "totalCholesterolMgdl": 186,
        "ldlCholesterolMgdl": 100,
        "hdlCholesterolMgdl": 45,
        "triglyceridesMgdl": 145,
        "creatinineMgdl": 0.85,
        "egfr": 86.8,
        "uricAcidMgdl": 6.2,
        "smokingStatus": "ACTIVE_SMOKER",
        "packYears": 18.6,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": false,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "BORDERLINE",
        "overallFitnessStatus": "FIT"
      },
      {
        "id": "mcu-uuid-W-00189-2025",
        "workerId": "worker-uuid-00189",
        "examinationDate": "2025-10-22",
        "heightCm": 171.0,
        "weightKg": 74.6,
        "bmi": 25.5,
        "waistCircumferenceCm": 86.1,
        "systolicBp": 127,
        "diastolicBp": 70,
        "restingHeartRate": 75,
        "fastingGlucoseMgdl": 99,
        "hba1cPercent": 7.5,
        "totalCholesterolMgdl": 202,
        "ldlCholesterolMgdl": 139,
        "hdlCholesterolMgdl": 37,
        "triglyceridesMgdl": 182,
        "creatinineMgdl": 1.18,
        "egfr": 77.5,
        "uricAcidMgdl": 6.3,
        "smokingStatus": "ACTIVE_SMOKER",
        "packYears": 18.6,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": false,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "NORMAL",
        "overallFitnessStatus": "FIT"
      },
      {
        "id": "mcu-uuid-W-00189-2026",
        "workerId": "worker-uuid-00189",
        "examinationDate": "2026-03-26",
        "heightCm": 171.0,
        "weightKg": 75.6,
        "bmi": 25.9,
        "waistCircumferenceCm": 88.2,
        "systolicBp": 134,
        "diastolicBp": 82,
        "restingHeartRate": 79,
        "fastingGlucoseMgdl": 105,
        "hba1cPercent": 7.9,
        "totalCholesterolMgdl": 185,
        "ldlCholesterolMgdl": 120,
        "hdlCholesterolMgdl": 43,
        "triglyceridesMgdl": 144,
        "creatinineMgdl": 0.9,
        "egfr": 83.5,
        "uricAcidMgdl": 5.7,
        "smokingStatus": "ACTIVE_SMOKER",
        "packYears": 18.6,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": false,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "NORMAL",
        "overallFitnessStatus": "FIT"
      }
    ],
    "dcuRecords": [
      {
        "id": "dcu-W-00189-20261124",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-11-24T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 134,
        "diastolicBp": 92,
        "restingHeartRate": 82,
        "spo2Percent": 100,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 7.0,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 6,
        "reactionTimeMs": 243,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261125",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-11-25T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 136,
        "diastolicBp": 80,
        "restingHeartRate": 86,
        "spo2Percent": 100,
        "bodyTemperatureC": 36.2,
        "sleepHoursLast24h": 7.5,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 18,
        "reactionTimeMs": 225,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261126",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-11-26T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 135,
        "diastolicBp": 85,
        "restingHeartRate": 82,
        "spo2Percent": 96,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 8.9,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 16,
        "reactionTimeMs": 254,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261127",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-11-27T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 132,
        "diastolicBp": 75,
        "restingHeartRate": 83,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.2,
        "sleepHoursLast24h": 5.6,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 12,
        "reactionTimeMs": 235,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261128",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-11-28T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 134,
        "diastolicBp": 83,
        "restingHeartRate": 86,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 6.7,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 16,
        "reactionTimeMs": 195,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261129",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-11-29T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 132,
        "diastolicBp": 85,
        "restingHeartRate": 85,
        "spo2Percent": 96,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 6.3,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 16,
        "reactionTimeMs": 249,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261201",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-01T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 135,
        "diastolicBp": 89,
        "restingHeartRate": 84,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 5.4,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 12,
        "reactionTimeMs": 204,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261202",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-02T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 130,
        "diastolicBp": 78,
        "restingHeartRate": 87,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 5.4,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 15,
        "reactionTimeMs": 247,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261203",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-03T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 133,
        "diastolicBp": 77,
        "restingHeartRate": 85,
        "spo2Percent": 98,
        "bodyTemperatureC": 35.4,
        "sleepHoursLast24h": 9.4,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 6,
        "reactionTimeMs": 235,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261205",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-05T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 140,
        "diastolicBp": 88,
        "restingHeartRate": 88,
        "spo2Percent": 95,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 7.7,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 11,
        "reactionTimeMs": 266,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261206",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-06T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 135,
        "diastolicBp": 84,
        "restingHeartRate": 77,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.1,
        "sleepHoursLast24h": 7.9,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 10,
        "reactionTimeMs": 219,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261208",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-08T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 137,
        "diastolicBp": 88,
        "restingHeartRate": 87,
        "spo2Percent": 96,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 6.1,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 19,
        "reactionTimeMs": 255,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261209",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-09T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 126,
        "diastolicBp": 88,
        "restingHeartRate": 82,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 8.2,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 6,
        "reactionTimeMs": 243,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261210",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-10T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 130,
        "diastolicBp": 84,
        "restingHeartRate": 77,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 8.0,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 16,
        "reactionTimeMs": 242,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261212",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-12T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 129,
        "diastolicBp": 81,
        "restingHeartRate": 83,
        "spo2Percent": 96,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 5.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 6,
        "reactionTimeMs": 242,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261213",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-13T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 139,
        "diastolicBp": 84,
        "restingHeartRate": 84,
        "spo2Percent": 95,
        "bodyTemperatureC": 36.4,
        "sleepHoursLast24h": 6.1,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 13,
        "reactionTimeMs": 204,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261214",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-14T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 132,
        "diastolicBp": 77,
        "restingHeartRate": 80,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 7.1,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 17,
        "reactionTimeMs": 245,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261215",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-15T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 133,
        "diastolicBp": 86,
        "restingHeartRate": 91,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.1,
        "sleepHoursLast24h": 6.9,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 20,
        "reactionTimeMs": 293,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261216",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-16T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 139,
        "diastolicBp": 86,
        "restingHeartRate": 91,
        "spo2Percent": 100,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 6.2,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 12,
        "reactionTimeMs": 227,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261217",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-17T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 129,
        "diastolicBp": 79,
        "restingHeartRate": 90,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 5.9,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 10,
        "reactionTimeMs": 211,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261218",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-18T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 133,
        "diastolicBp": 80,
        "restingHeartRate": 80,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 5.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 19,
        "reactionTimeMs": 226,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261219",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-19T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 127,
        "diastolicBp": 74,
        "restingHeartRate": 85,
        "spo2Percent": 99,
        "bodyTemperatureC": 37.0,
        "sleepHoursLast24h": 7.8,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 14,
        "reactionTimeMs": 238,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261220",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-20T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 134,
        "diastolicBp": 86,
        "restingHeartRate": 86,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.4,
        "sleepHoursLast24h": 5.4,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 13,
        "reactionTimeMs": 222,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261221",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-21T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 129,
        "diastolicBp": 79,
        "restingHeartRate": 80,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.8,
        "sleepHoursLast24h": 7.4,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 11,
        "reactionTimeMs": 315,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261222",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-22T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 128,
        "diastolicBp": 82,
        "restingHeartRate": 78,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.4,
        "sleepHoursLast24h": 6.2,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 15,
        "reactionTimeMs": 273,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261223",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-23T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 138,
        "diastolicBp": 93,
        "restingHeartRate": 79,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 6.4,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 15,
        "reactionTimeMs": 175,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261224",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-24T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 142,
        "diastolicBp": 87,
        "restingHeartRate": 83,
        "spo2Percent": 98,
        "bodyTemperatureC": 35.8,
        "sleepHoursLast24h": 6.4,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 6,
        "reactionTimeMs": 217,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00189-20261228",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-28T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 136,
        "diastolicBp": 83,
        "restingHeartRate": 90,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.0,
        "sleepHoursLast24h": 7.2,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 19,
        "reactionTimeMs": 258,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261229",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-29T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 122,
        "diastolicBp": 83,
        "restingHeartRate": 87,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 6.0,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 17,
        "reactionTimeMs": 229,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00189-20261231",
        "workerId": "worker-uuid-00189",
        "recordedAt": "2026-12-31T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 139,
        "diastolicBp": 91,
        "restingHeartRate": 93,
        "spo2Percent": 96,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 4.7,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 19,
        "reactionTimeMs": 266,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      }
    ]
  },
  "W-00190": {
    "worker": {
      "id": "worker-uuid-00190",
      "pseudonymId": "W-00190",
      "nameSynthetic": "Hendra Pangestu",
      "age": 53,
      "gender": "MALE",
      "department": "HSSE & Occupational Clinic",
      "jobTitle": "Safety Inspector",
      "jobHazardCategory": "LOW",
      "shiftPattern": "DAY_SHIFT_ONLY",
      "tenureMonths": 45,
      "isActive": true
    },
    "mcuRecords": [
      {
        "id": "mcu-uuid-W-00190-2024",
        "workerId": "worker-uuid-00190",
        "examinationDate": "2024-05-20",
        "heightCm": 163.8,
        "weightKg": 73.8,
        "bmi": 27.5,
        "waistCircumferenceCm": 91.5,
        "systolicBp": 140,
        "diastolicBp": 85,
        "restingHeartRate": 92,
        "fastingGlucoseMgdl": 90,
        "hba1cPercent": 7.3,
        "totalCholesterolMgdl": 256,
        "ldlCholesterolMgdl": 181,
        "hdlCholesterolMgdl": 48,
        "triglyceridesMgdl": 115,
        "creatinineMgdl": 1.04,
        "egfr": 63.0,
        "uricAcidMgdl": 4.8,
        "smokingStatus": "ACTIVE_SMOKER",
        "packYears": 27.4,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": true,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "NORMAL",
        "overallFitnessStatus": "FIT_WITH_RESTRICTION"
      },
      {
        "id": "mcu-uuid-W-00190-2025",
        "workerId": "worker-uuid-00190",
        "examinationDate": "2025-06-16",
        "heightCm": 163.8,
        "weightKg": 74.1,
        "bmi": 27.6,
        "waistCircumferenceCm": 91.5,
        "systolicBp": 135,
        "diastolicBp": 92,
        "restingHeartRate": 70,
        "fastingGlucoseMgdl": 95,
        "hba1cPercent": 7.8,
        "totalCholesterolMgdl": 272,
        "ldlCholesterolMgdl": 216,
        "hdlCholesterolMgdl": 29,
        "triglyceridesMgdl": 169,
        "creatinineMgdl": 0.78,
        "egfr": 68.5,
        "uricAcidMgdl": 7.0,
        "smokingStatus": "ACTIVE_SMOKER",
        "packYears": 27.4,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": true,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": false,
        "onStatinDrugs": true,
        "restingEcgInterpretation": "BORDERLINE",
        "overallFitnessStatus": "FIT_WITH_RESTRICTION"
      },
      {
        "id": "mcu-uuid-W-00190-2026",
        "workerId": "worker-uuid-00190",
        "examinationDate": "2026-08-14",
        "heightCm": 163.8,
        "weightKg": 75.0,
        "bmi": 28.0,
        "waistCircumferenceCm": 94.8,
        "systolicBp": 165,
        "diastolicBp": 104,
        "restingHeartRate": 79,
        "fastingGlucoseMgdl": 101,
        "hba1cPercent": 7.9,
        "totalCholesterolMgdl": 236,
        "ldlCholesterolMgdl": 145,
        "hdlCholesterolMgdl": 46,
        "triglyceridesMgdl": 130,
        "creatinineMgdl": 1.1,
        "egfr": 59.5,
        "uricAcidMgdl": 4.0,
        "smokingStatus": "ACTIVE_SMOKER",
        "packYears": 27.4,
        "hasDiabetesHistory": true,
        "hasHypertensionHistory": true,
        "familyCardioHistory": false,
        "onAntihypertensiveDrugs": true,
        "onStatinDrugs": false,
        "restingEcgInterpretation": "BORDERLINE",
        "overallFitnessStatus": "UNFIT"
      }
    ],
    "dcuRecords": [
      {
        "id": "dcu-W-00190-20261127",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-11-27T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 157,
        "diastolicBp": 97,
        "restingHeartRate": 81,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.0,
        "sleepHoursLast24h": 7.2,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 11,
        "reactionTimeMs": 241,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261128",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-11-28T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 164,
        "diastolicBp": 108,
        "restingHeartRate": 83,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.7,
        "sleepHoursLast24h": 7.7,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 16,
        "reactionTimeMs": 203,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261129",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-11-29T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 155,
        "diastolicBp": 96,
        "restingHeartRate": 82,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.8,
        "sleepHoursLast24h": 6.0,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 12,
        "reactionTimeMs": 178,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261130",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-11-30T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 168,
        "diastolicBp": 113,
        "restingHeartRate": 89,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 7.3,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 10,
        "reactionTimeMs": 261,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261201",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-01T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 157,
        "diastolicBp": 101,
        "restingHeartRate": 86,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 5.7,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 19,
        "reactionTimeMs": 230,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261202",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-02T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 163,
        "diastolicBp": 97,
        "restingHeartRate": 86,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 7.3,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 15,
        "reactionTimeMs": 222,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261203",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-03T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 157,
        "diastolicBp": 97,
        "restingHeartRate": 86,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.2,
        "sleepHoursLast24h": 7.5,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 20,
        "reactionTimeMs": 223,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261205",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-05T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 166,
        "diastolicBp": 108,
        "restingHeartRate": 80,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 6.3,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 13,
        "reactionTimeMs": 241,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261206",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-06T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 160,
        "diastolicBp": 94,
        "restingHeartRate": 83,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.4,
        "sleepHoursLast24h": 5.7,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 11,
        "reactionTimeMs": 253,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261207",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-07T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 164,
        "diastolicBp": 102,
        "restingHeartRate": 91,
        "spo2Percent": 97,
        "bodyTemperatureC": 37.3,
        "sleepHoursLast24h": 6.7,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 14,
        "reactionTimeMs": 243,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261208",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-08T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 165,
        "diastolicBp": 101,
        "restingHeartRate": 85,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 5.5,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 8,
        "reactionTimeMs": 291,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261209",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-09T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 171,
        "diastolicBp": 111,
        "restingHeartRate": 75,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 7.6,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 12,
        "reactionTimeMs": 269,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261210",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-10T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 161,
        "diastolicBp": 103,
        "restingHeartRate": 88,
        "spo2Percent": 96,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 6.9,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 9,
        "reactionTimeMs": 238,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261211",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-11T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 161,
        "diastolicBp": 95,
        "restingHeartRate": 89,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 6.8,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 17,
        "reactionTimeMs": 227,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261212",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-12T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 173,
        "diastolicBp": 110,
        "restingHeartRate": 88,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.1,
        "sleepHoursLast24h": 6.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 8,
        "reactionTimeMs": 234,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261214",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-14T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 158,
        "diastolicBp": 101,
        "restingHeartRate": 84,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 6.9,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 10,
        "reactionTimeMs": 262,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261215",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-15T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 165,
        "diastolicBp": 99,
        "restingHeartRate": 90,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 5.6,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 6,
        "reactionTimeMs": 273,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261217",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-17T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 163,
        "diastolicBp": 97,
        "restingHeartRate": 87,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 6.8,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 16,
        "reactionTimeMs": 233,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261218",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-18T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 154,
        "diastolicBp": 100,
        "restingHeartRate": 84,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.9,
        "sleepHoursLast24h": 7.9,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 18,
        "reactionTimeMs": 204,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261219",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-19T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 169,
        "diastolicBp": 103,
        "restingHeartRate": 82,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 8.0,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 7,
        "reactionTimeMs": 203,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261220",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-20T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 165,
        "diastolicBp": 98,
        "restingHeartRate": 93,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 5.9,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 10,
        "reactionTimeMs": 220,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261221",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-21T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 171,
        "diastolicBp": 109,
        "restingHeartRate": 85,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.4,
        "sleepHoursLast24h": 6.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 16,
        "reactionTimeMs": 243,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261222",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-22T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 169,
        "diastolicBp": 111,
        "restingHeartRate": 88,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.5,
        "sleepHoursLast24h": 8.3,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 17,
        "reactionTimeMs": 267,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261223",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-23T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 169,
        "diastolicBp": 101,
        "restingHeartRate": 82,
        "spo2Percent": 98,
        "bodyTemperatureC": 36.3,
        "sleepHoursLast24h": 8.3,
        "caffeineIntakeCups": 1,
        "cigarettesTodayCount": 14,
        "reactionTimeMs": 231,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261224",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-24T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 165,
        "diastolicBp": 101,
        "restingHeartRate": 85,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.4,
        "sleepHoursLast24h": 6.4,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 15,
        "reactionTimeMs": 268,
        "chestPainFlag": true,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261225",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-25T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 158,
        "diastolicBp": 99,
        "restingHeartRate": 72,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.8,
        "sleepHoursLast24h": 7.0,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 13,
        "reactionTimeMs": 202,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261226",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-26T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 164,
        "diastolicBp": 102,
        "restingHeartRate": 95,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 5.7,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 19,
        "reactionTimeMs": 255,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "PARAMEDIC_ASSISTED"
      },
      {
        "id": "dcu-W-00190-20261227",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-27T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 167,
        "diastolicBp": 100,
        "restingHeartRate": 87,
        "spo2Percent": 97,
        "bodyTemperatureC": 36.6,
        "sleepHoursLast24h": 7.6,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 19,
        "reactionTimeMs": 236,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261228",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-28T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 167,
        "diastolicBp": 109,
        "restingHeartRate": 83,
        "spo2Percent": 96,
        "bodyTemperatureC": 37.0,
        "sleepHoursLast24h": 6.8,
        "caffeineIntakeCups": 0,
        "cigarettesTodayCount": 11,
        "reactionTimeMs": 227,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": true,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      },
      {
        "id": "dcu-W-00190-20261230",
        "workerId": "worker-uuid-00190",
        "recordedAt": "2026-12-30T06:30:00Z",
        "shiftType": "DAY_SHIFT",
        "systolicBp": 160,
        "diastolicBp": 92,
        "restingHeartRate": 74,
        "spo2Percent": 99,
        "bodyTemperatureC": 36.8,
        "sleepHoursLast24h": 5.8,
        "caffeineIntakeCups": 2,
        "cigarettesTodayCount": 6,
        "reactionTimeMs": 210,
        "chestPainFlag": false,
        "shortnessOfBreathFlag": false,
        "dizzinessFlag": false,
        "palpitationsFlag": false,
        "entryMode": "SELF_SERVICE_KIOSK"
      }
    ]
  }
};

export function getDemoWorker(pseudonymId: string): DemoWorkerData {
  if (DEMO_WORKERS[pseudonymId]) {
    return DEMO_WORKERS[pseudonymId];
  }
  // Default to W-00192 if not found
  return DEMO_WORKERS['W-00192'];
}
